def mobd_dict():
    
    mobd_list = {
        
        'Low Birth Weight': 'lbw',
        #'Low Birth Weight Indicator': 'lbw_ind',
        'Very Low Weight Rate': 'vlbw',
        #'Very Low Weight Rate Indicator': 'vlbw_ind',
        'Premature Births': 'premature',
        #'Premature Births Indicator': 'premature_ind',
        'Births to Women Under 18': 'under_18',
        #'Births to Women Under 18 Indicator': 'under_18_ind',
        'Births to Women Over 40': 'over_40',
        #'Births to Women Over 40 Indicator': 'over_40_ind',
        'Births to Unmarried Women': 'unmarried',
        #'Births to Unmarried Women Indicator': 'unmarried_ind',
        'No Care in 1st Trimester': 'late_care',
        #'No Care in 1st Trimester Indicator': 'late_care_ind',
        'Infant Mortality': 'im',
        #'Infant Mortality Indicator': 'im_ind',
        #'Infant Mortality (White)': 'im_wh',
        #'Infant Mortality (White) indicator': 'im_wh_ind',
        #'Infant Mortality (Black)': 'im_bl',
        #'Infant Mortality (Black) Indicator': 'im_bl_ind',
        #'Infant Mortality (Hispanic)': 'im_h',
        #'Infant Mortality (Hispanic) Indicator': 'im_h_ind',
        #'Infant Mortality (Neonatal)': 'im_neonatal',
        #'Infant Mortality (Neonatal) Indicator': 'im_neonatal_ind',
        #'Infant Mortality (Postneonatal)': 'im_postneonatal',
        #'Infant Mortality (Postneonatal) Indicators': 'im_postneonatal_ind',
        'Breast Cancer Deaths': 'breast_cancer',
        #'Breast Cancer Deaths Indicator': 'breast_cancer_ind',
        'Colon Cancer Deaths': 'col_cancer',
        #'Colon Cancer Deaths Indicators': 'col_cancer_ind',
        'Coronary Heart Disease Deaths': 'chd',
        #'Coronary Heart Disease Deaths Indicator': 'chd_ind',
        'Homicide Deaths': 'homicide',
        #'Homicide Deaths Indicator': 'homicide_ind',
        'Lung Cancer Deaths': 'lung_cancer',
        #'Lung Cancer Deaths Indicator': 'lung_cancer_ind',
        'Motor Vehicle Deaths': 'mva',
        #'Motor Vehicle Deaths Indicators': 'mva_ind',
        'Stroke Deaths': 'stroke',
        #'Stroke Deaths Indicators': 'stroke_ind',
        'Suicide Deaths': 'suicide',
        #'Suicide Deaths Indicator': 'suicide_ind',
        'Injury Deaths': 'injury',
        #'Injury Deaths Indicator': 'injury_ind',
        'Total Births': 'total_birth',
        'Total Deaths' : 'total_death'
        
        }
    
    return mobd_list